name: Auto Optimize & Merge CSS

on:
  push:
    branches:
      - main

# 🔑 GITHUB ACTIONS BOT KO WRITE ACCESS DENE KE LIYE
permissions:
  contents: write

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Minifier Tool
        run: npm install -g clean-css-cli

      - name: Merge and Minify main and search CSS
        run: |
          # main.css aur search.css ko jodkar search-main.css banayega
          cleancss -o assets/css/search-main.css assets/css/main.css assets/css/search.css

      - name: Commit and Push Compiled Joint File
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/css/search-main.css
          git diff-index --quiet HEAD || git commit -m "chore: automatic production search-main.css bundle generated"
          git push
